### ISSUE TITLE
Is there a way to track % of correct prediction among participant on a league or event

### ISSUE THREAD

**Issue by Gaalee** [mckernant1/lol-predictions-bot#2]
Hi, pretty much the title, my friend and I are going to use your bot to predict on worlds matchs and we would love to track how people are doing at it. Is there already a way to do that ?

If not, are  you planning on adding something like that in the future ? Thanks loving your bot.

**Comment by mckernant1** [comment]
Hello! Glad you like the bot!

There are 2 ways to track matches: 
- You can use the `!report` command to get the most recent matches.
- Or you can use the `!stats` command to get your overall correct percentage for the tournament.

I think what you're looking for is `!stats worlds`.

You can also do `!info` or `!info predict` to get more help!
Let me know if you're looking for something different
